print("Hi, I'm Elle")
print("I'm going to ask you a few questions...")
input("")
name = input ("What is your name? ")
print(f"Nice to meet you {name}!")
print("***************************")
print("")
input("How has your day been? ")
print("***************************")
print("")
animal = input("What is your favorite animal? ")
print(f"{animal} are my favorite too!")
print("***************************")
print("")
food = input("What is your favorite food? ")
print(f"I like {food} too.")
print("***************************")
print("")
sport = input("Do you play any sports? ")
if sport == "yes":
    print("Me too!")
if sport =="no":
      print ("That's okay")
else:print("")    
print("***************************")
print("")
input("What is your favorite color? ")
print("****************************")
print("")
input("Do you have any pets? ")
print("***************************")
print("")
school = input("What is your favorite school subject? ")
if school == "pe":
     print("That's my favorite too!")
else: print()
print("***************************")
print("")
print("Thanks for talking with me!")
print(f"Bye {name}")