print("Hi, I'm Elle")
print("I'm going to ask you a few questions...")
input()
name = input ("What is your name?")
print(f"Nice to meet you {name}!")
print("How has your day been?")
input()
animal = input("What is your favorite animal?")
print(f"{animal}s are my favorite too!")
food = input("What is your favorite food?")
print(f"I like {food} too.")
print("Do you play any sports?")
print("What do you play?")